import { createClient } from "@/actions/client";

import type { ClientData } from "@/schemas/client";

export async function createMockClients() {
  for (const client of MOCK_CLIENTS_DATA) {
    const res = await createClient(client);

    if (!res.ok) {
      console.error("Dados do Cliente: ", client);
    }

    console.log(res.message);
  }
}

export const MOCK_CLIENTS_DATA: ClientData[] = [
  {
    id: 1,
    document: "12345678000190",
    registration: "111222333",
    socialName: "Tecnologia Inovadora Ltda.",
    name: "InovaTech",
    email: "contato@inovatech.com",
    cellphone: "31998765432",
    payment: 30,
    currency: "BRL",
    address: {
      street: "Avenida Afonso Pena",
      country: "Brasil",
      city: "Belo Horizonte",
      state: "MG",
      number: "1500",
      district: "Centro",
      complement: "Sala 1201",
    },
  },
  {
    id: 2,
    document: "98765432109",
    registration: "9876543210",
    socialName: "Comércio Varejista Estilo S.A.",
    name: "Estilo & Cia",
    email: "vendas@estiloecia.com.br",
    cellphone: "11987654321",
    payment: 15,
    currency: "BRL",
    address: {
      street: "Rua Augusta",
      country: "Brasil",
      city: "São Paulo",
      state: "SP",
      number: "2500",
      district: "Cerqueira César",
      complement: "Loja 3",
    },
  },
  {
    id: 3,
    document: "87654321000112",
    registration: "109876543210",
    socialName: "Soluções Digitais Globais Inc.",
    name: "Global Solutions",
    email: "support@globalsolutions.io",
    cellphone: "21976543210",
    payment: 90,
    currency: "USD",
    address: {
      street: "Avenida Rio Branco",
      country: "Brasil",
      city: "Rio de Janeiro",
      state: "RJ",
      number: "1",
      district: "Centro",
    },
  },
  {
    id: 4,
    document: "23456789000145",
    registration: "5432167890",
    socialName: "Padaria Sonho de Valsa Ltda.",
    name: "Padaria Sonho",
    email: "pedidos@padariasonho.com",
    cellphone: "41965432109",
    payment: 7,
    currency: "BRL",
    address: {
      street: "Rua das Flores",
      country: "Brasil",
      city: "Curitiba",
      state: "PR",
      number: "300",
      district: "Centro",
    },
  },
  {
    id: 5,
    document: "10293847560",
    registration: "222333444",
    socialName: "Finanças Consultoria Pessoal",
    name: "Seu Futuro Financeiro",
    email: "consultor@seufuturo.com",
    cellphone: "51954321098",
    payment: 120,
    currency: "USD",
    address: {
      street: "Avenida Borges de Medeiros",
      country: "Brasil",
      city: "Porto Alegre",
      state: "RS",
      number: "512",
      district: "Praia de Belas",
      complement: "Conjunto 802",
    },
  },
  {
    id: 6,
    document: "87654321000145",
    registration: "876543210",
    socialName: "Agronegócio do Cerrado Exportações",
    name: "Cerrado Agro",
    email: "export@cerradoagro.com",
    cellphone: "62943210987",
    payment: 45,
    currency: "USD",
    address: {
      street: "Avenida 85",
      number: "2000",
      district: "Setor Marista",
      city: "Goiânia",
      state: "GO",
      country: "Brasil",
    },
  },
  {
    id: 7,
    document: "12312312312",
    registration: "1231231234",
    socialName: "Design de Interiores Aconchego ME",
    name: "Lar Decor",
    email: "contato@lardecor.design",
    cellphone: "71932109876",
    payment: 60,
    currency: "BRL",
    address: {
      street: "Rua da Fonte do Boi",
      number: "99",
      district: "Rio Vermelho",
      city: "Salvador",
      state: "BA",
      country: "Brasil",
    },
  },
  {
    id: 8,
    document: "45678912000167",
    registration: "45678912345",
    socialName: "Transportadora Veloz do Norte Ltda.",
    name: "Norte Cargas",
    email: "logistica@nortecargas.com.br",
    cellphone: "92921098765",
    payment: 10,
    currency: "BRL",
    address: {
      street: "Avenida Djalma Batista",
      number: "482",
      district: "Parque 10 de Novembro",
      city: "Manaus",
      state: "AM",
      country: "Brasil",
      complement: "Galpão C",
    },
  },
  {
    id: 9,
    document: "89012345000189",
    registration: "890123456789",
    socialName: "Engenharia e Construção Forte Eireli",
    name: "Forte Engenharia",
    email: "engenharia@forte.eng.br",
    cellphone: "85910987654",
    payment: 180,
    currency: "BRL",
    address: {
      street: "Avenida Beira Mar",
      number: "3000",
      district: "Meireles",
      city: "Fortaleza",
      state: "CE",
      country: "Brasil",
    },
  },
  {
    id: 10,
    document: "32165498701",
    registration: "987987987",
    socialName: "Academia Corpo em Movimento",
    name: "Fit Club",
    email: "matricula@fitclub.com.br",
    cellphone: "61998761234",
    payment: 20,
    currency: "BRL",
    address: {
      street: "SCS Quadra 07 Bloco A",
      number: "100",
      district: "Asa Sul",
      city: "Brasília",
      state: "DF",
      country: "Brasil",
      complement: "Loja 12",
    },
  },
];
